#!/bin/bash
set -ex

# if [[ ":$PATH:" != *":$HOME/dotfiles-main/rcm/usr/bin/:"* ]]; then
# 	export PATH="$HOME/dotfiles-main/rcm/usr/bin/:$PATH"
# fi

rm -rf "$HOME"/dotfiles-main || true
if command -v git &>/dev/null; then
  git clone https://github.com/bes-internal/dotfiles.git "$HOME"/dotfiles-main
else
  wget https://github.com/bes-internal/dotfiles/archive/refs/heads/main.zip -O "$HOME"/dotfiles-main.zip
  unzip -q "$HOME"/dotfiles-main.zip -d "$HOME"
  rm "$HOME"/dotfiles-main.zip
  chmod +x "$HOME"/dotfiles-main/bin/dfm
fi

"$HOME"/dotfiles-main/bin/dfm install -v

# exec $SHELL -l

# curl -fsSL https://xn--txe.net/init |bash -

