#!/bin/bash
set -x

rm -rf "$HOME"/dotfiles-main || true
if command -v git &>/dev/null; then
  git clone https://github.com/bes-internal/dotfiles.git "$HOME"/dotfiles-main
else
  wget https://github.com/bes-internal/dotfiles/archive/refs/heads/main.zip -O "$HOME"/dotfiles-main.zip
  unzip -q "$HOME"/dotfiles-main.zip -d "$HOME"
  rm "$HOME"/dotfiles-main.zip
fi
#chmod +x "$HOME"/dotfiles-main/dfm

"$HOME"/dotfiles-main/dfm install -v

# shell = $(ps -p $$ -o comm=)

#source "$HOME"/.bashrc
exec $SHELL -i -l


# curl -fsSL https://xn--txe.net/init |bash -

